# Auto generated by $ETC_APP, DO NOT EDIT!

if [[ \$(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_chezmoi $ETC_APP
else
    complete -o default -o nospace -F __start_chezmoi $ETC_APP
fi
