# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

project = 'chezetc'
author = 'Shengyu Zhang'
copyright = '2025, ' + author

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.email',
    'sphinx.ext.githubpages',
    'sphinx_last_updated_by_git',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.rst']

# Options for internationalisation -------------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en_US'

# -- Options for HTML output -------------------------------------------------

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ['custom.css']

html_baseurl = 'https://silverrainz.me/chezetc'
html_favicon = '_static/chezmoi.svg'

# HTML theme configuration
html_theme = 'pydata_sphinx_theme'
html_theme_options = {}

html_sidebars = {}

# Show only Single page
## Hide navbar.
html_theme_options['navbar_start'] = []
html_theme_options['navbar_center'] = []
html_theme_options['navbar_end'] = ['navbar-icon-links']
html_theme_options['navbar_persistent'] = []
## Hide sidebars.
## See also https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/no-sidebar.html
html_sidebars['*'] = [] # primary
html_theme_options['secondary_sidebar_items'] = {'*': []} # secondary
## Unrelated elements
html_theme_options['show_prev_next'] = False,

# Custom footer.
html_theme_options['footer_start'] = ['theme-switcher'] # TODO: 'version-switcher'
html_theme_options['footer_end'] = ['copyright', 'last-updated', 'sphinx-version', 'theme-version']

html_last_updated_fmt = '%Y-%m-%d'

# -- Per-extension configuration ---------------------------------------------------

extensions.append('sphinxcontrib.gtagjs')
gtagjs_ids = ['G-FYHS50G6DL']
